#= require 'jquery'
$(document).ready ->
  # $('.video-container').fitVids customSelector: 'iframe[src^=\'player.vimeo.com\']'
  $('#toggle').click ->
    # alert("lol");
    $('nav').toggleClass 'visible'
    $('nav').toggleClass 'transition-dismiss'
    # $(".index-site-title").toggleClass("hide");
    # $('.logo').toggleClass 'hide'
    # $("html").toggleClass("fixed");
    # $('#container').toggleClass 'scroll'
    $('#toggle').toggleClass 'active'
    # $('#footer').toggleClass 'hide'
    $('body').toggleClass 'transition-dismiss'
    # $('body, html').toggleClass 'overflow'
    # if navigator.userAgent.match('CriOS')
      # $('html').toggleClass 'fixed'
    return
  # $("#dismissNav").click(function() {
  #   // alert("lol");
  #   $("nav").removeClass("visible");
  #   $("#dismissNav").removeClass("visible");
  # });
  # $('#additional').click ->
  #   # alert("lol");
  #   $('.additional').toggleClass 'visible'
  #   return
  # $('#toggle-text').click ->
  #   # alert("lol");
  #   $('section.more').toggleClass 'visible'
  #   $('article.studio header').toggleClass 'margin'
    return
  # $('.site-title').mouseover ->
  #   # alert("lol");
  #   $('nav li').toggleClass 'rollout'
  #   return
  return


$document = $(document)
$document.scroll ->
  if $('body').is('.index')
    return
  else
    if $document.scrollTop() >= 110
      # user scrolled 50 pixels or more;
      # do stuff
      $('header#header').addClass 'notOnTop'
      $('#container').addClass 'margin-top'
      $('.description-container').addClass 'margin-top'
    else
      $('header#header').removeClass 'notOnTop'
    return

lastScrollTop = 0
$(window).scroll (event) ->
  if $('body').is('.index')
    return
  else
    st = $(this).scrollTop()
    if st > lastScrollTop
      $('header#header').removeClass 'scrollup'
    else
      $('header#header').addClass 'scrollup'
      $('header#header').addClass 'opacity'
      $('header#header').removeClass 'scrolldown'
    if st < 60
      $('header#header').removeClass 'scrollup'
      $('header#header').removeClass 'opacity'
      $('#container').removeClass 'margin-top'
      $('.description-container').removeClass 'margin-top'
    # if (st > 55) {
    #     $("header#header").addClass("scrolldown");       
    # }
    lastScrollTop = st
    return


# $(document).ready ->
#   bodyWidth = $('body').width()
#   vwptWidth = $(window).width()
#   bpTwo = '400px'
#   if vwptWidth > bpTwo
#     $('body').addClass 'red'
#   return
# $(document).ready ->
#   bodyHeight = $('body').height()
#   vwptHeight = $(window).height()
#   if vwptHeight > bodyHeight
#     # $("footer#footer").css("position","fixed").css("bottom",0).css("width:",100%);
#     $('footer#footer').addClass 'stick'
#     $('.toggle-nav').addClass 'no-scroll'
#   # else if (vwptHeight < bodyHeight){
#   #   $("footer#footer").removeClass("stick");
#   #   $(".toggle-nav").addClass("test");
#   #   $("footer#footer").css("background","red");
#   # }
#   return

# ---
# generated by js2coffee 2.1.0